export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'

export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const LOGOUT = 'LOGOUT'

export const GET_USER_REQUESTED = 'GET_USER_REQUESTED'
export const FETCH_FAILED = 'FETCH_FAILED'
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED'

export const UPDATE_USER_REQUESTED = 'UPDATE_USER_REQUESTED'
export const UPDATE_SUCCEEDED = 'UPDATE_SUCCEEDED'
export const UPDATE_FAILED = 'UPDATE_FAILED'